version: "3.9"

networks:
  main:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    expose:
      - 8000
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    networks:
      - main
  server:
    image: nginx:stable-alpine3.17-slim
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - main
    depends_on:
      - app