version: "3.9"

networks:
  main:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    expose:
      - 8000
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    networks:
      - main
  server:
    image: nginx:stable-alpine3.17-slim
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/certbot/conf:/etc/nginx/ssl
      - ./docker/certbot/data:/var/www/certbot
    networks:
      - main
    depends_on:
      - app
  certbot:
    image: certbot/certbot
    volumes: 
      - ./docker/certbot/conf:/etc/letsencrypt
      - ./docker/certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email aslampangestu@gmail.com -d three-papers-smell-brightly.a276.dcdg.xyz --agree-tos
    depends_on:
      - server