version: "3.9"

networks:
  main:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    expose:
      - 8000
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    networks:
      - main
  server:
    image: nginx:stable-alpine3.17-slim
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/certbot/conf:/etc/nginx/ssl
      - ./docker/certbot/data:/var/www/certbot
    networks:
      - main
    depends_on:
      - app
  certbot:
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path=/var/www/certbot --email aslampangesty@gmail.com --agree-tos --no-eff-email -d three-papers-smell-brightly.a276.dcdg.xyz
    volumes:
      - ./docker/certbot/conf:/etc/letsencrypt
      - ./docker/certbot/logs:/var/log/letsencrypt
      - ./docker/certbot/data:/var/www/certbot
    depends_on:
      - server