version: "3.9"

networks:
  main:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    expose:
      - 8000
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    networks:
      - main
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
  server:
    image: nginx:stable-alpine3.17-slim
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    networks:
      - main
    depends_on:
      - app
      - certbot