version: "3.9"

networks:
  main:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    networks:
      - main
  server:
    image: nginx:stable-alpine3.17-slim
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - main