name: Continuous Deployment
 
on: 
  push:
    branches:
      - master
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
    - name: SSH and deploy app
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        command_timeout: 200m
        script: |
          cd ~/forum-api
          git pull origin master
          docker-compose rm -f
          docker-compose pull
          docker-compose build --no-cache app
          docker-compose build --no-cache server
          docker-compose up -d app
          docker-compose up -d server